export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCHING_COIN_DATA_SUCCESS = "FETCHING_COIN_DATA_SUCCESS";
export const FETCHING_COIN_DATA_FAIL = "FETCHING_COIN_DATA_FAIL";

export const FECTHING_NEWS = 'FETCHING_NEWS';
export const FECTHING_NEWS_SUCCESS = 'FECTHING_NEWS_SUCCESS';
export const FECTHING_NEWS_FAIL = 'FECTHING_NEWS_FAIL';
